# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb2c4bc0fa735603c3fa84806e47cd496ca995e274ec6bed6728e5b24d52bd068040f16b17fcf650358f4c63956679d5d0f480082868776ad5e5152103aacb48

test:
  secret_key_base: c5adaff0ad93d7642381b51225a9109b514fd6a625f33ca810903cef0d54fad5ba781edb2d24c830cf58f28fcf6c75f26887be13c1a8aae66810af348e0eea61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
